### ISSUE TITLE
Redundant duplicity in css

### ISSUE THREAD

**Issue by Klemo1997** [Squagilli/squugle-homepage#1]
Using this type of styling is a bad practice, imagine wanting to change/delete/add new property. It will be same and you will have to do the same thing 7 times. In this case it is better to use class selector, so instead of doing it like this

```css
#letter-1 {
    flex-grow: 1;
    height: 10px;
    width: 10px;
    text-align: center;
}

#letter-2 {
    flex-grow: 1;
    height: 10px;
    width: 10px;
    text-align: center;
}

#letter-1:hover, #letter-2:hover, #letter-3:hover, #letter-4:hover, #letter-5:hover, #letter-6:hover, #letter-7:hover  {
    color: #0710FA;
    font-size: 150px;
    margin-top: -20px;
}
#letter-1, #letter-2, #letter-3, #letter-4, #letter-5, #letter-6, #letter-7 {
    font-family: 'Questrial', sans-serif;
    font-size: 150px;
    text-align: center;
    

    padding: 10px;
    margin: 10px;
}
...
```
do it like this:
```css
.letter-item {
    flex-grow: 1;
    height: 10px;
    width: 10px;
    text-align: center;

    font-family: 'Questrial', sans-serif;
    font-size: 150px;
    text-align: center;
    
    padding: 10px;
    margin: 10px;
}

.letter-item:hover {
    color: #0710FA;
    font-size: 150px;
    margin-top: -20px;
}
```

and update selectors in html file as well:
```html
 <div class="letter-item" data-order="1">S</div> 
 <div class="letter-item" data-order="2">q</div>
```

Also it is better to use `em/rem` units instead of `px`, because they are relative (px is absolute). That means they will change with system font size (better readability for tablet/phone).

Also when values are repeating, consider using css variables (same thing as before, so when you need to change the value, you will just do it in one place)

Variables with theme colors are necessary for nice and pure design, for example variable like `--color-hover` and then using it on all hover effects results to better overall color balance.

Another advantage is that when you want to add dark theme for example, you just figure all color variaables dark equivalents and you got it

Reference on css variables:
https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties
